name: seaber

services:
  database:
    image: postgres:17.2
    container_name: seaber-database
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
    networks:
      - network

  server:
    image: seaber/server:latest
    build: ./
    container_name: seaber-server
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT:?SERVER_PORT is not set}
      SERVER_POSTGRES_URL: ${SERVER_POSTGRES_URL:?SERVER_POSTGRES_URL is not set}
    networks:
      - network
    depends_on:
      - database

volumes:
  pg-data:

networks:
  network:
    name: seaber-network